apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: couchbase
  namespace: default # <1>
  labels:
    app: couchbase
spec:
  endpoints:
  - port: metrics       # <2>
    interval: 5s        # <3>
  namespaceSelector:
    matchNames:
    - default # <4>
  selector:
    matchLabels:
      app: couchbase # <5>

