apiVersion: v1
kind: Service
metadata:
  name: couchbase-metrics
  namespace: default # <1>
  labels:
    app: couchbase
spec:
  ports:
  - name: metrics
    port: 9091 # <2>
    protocol: TCP
  selector:
    app: couchbase
    couchbase_cluster: cb-example # <3>
